### ISSUE TITLE
Solution: Layout to code

### ISSUE THREAD

**Issue by Rachel-Norman** [Rachel-Norman/layout-to-code#1]
@wendywarren

[norman-rachel-solution-layout-to-code.m4a.zip](https://github.com/Rachel-Norman/layout-to-code/files/8012812/norman-rachel-solution-layout-to-code.m4a.zip)

1. header — Website masthead
2. h1 — Heading 1, most important content
3. nav — Navigation of the website
4. ul — Unordered list
5. li — A list item 
6. a — Link to another part of the website
7. div — Divides content into logical groups
8. img — Image
9. img — Image
10. p — Paragraph of text

**Comment by wendywarren** [comment]
Good job @Rachel-Norman!
